target_os="android"
target_cpu="arm64"
skia_use_fonthost_mac=false
skia_use_freetype=true
skia_use_system_freetype2=false
skia_use_freetype_woff2=false
skia_use_freetype_svg=true
skia_use_freetype_zlib=true
skia_use_freetype_zlib_bundled=true
skia_use_fontconfig=false
skia_enable_fontmgr_android=true
skia_enable_fontmgr_android_ndk=false
skia_use_vulkan=true
extra_cflags=["-mno-outline-atomics"]
